ALTER TABLE subscriptions ADD COLUMN unit_price_cents INTEGER NOT NULL DEFAULT 0;
ALTER TABLE subscriptions ADD COLUMN flat_fee_cents INTEGER NOT NULL DEFAULT 0;
ALTER TABLE subscriptions ADD COLUMN min_devices INTEGER NOT NULL DEFAULT 0;
ALTER TABLE subscriptions ADD COLUMN grace_days INTEGER NOT NULL DEFAULT 0;
